[workspace]
channels = ["conda-forge"]
name = "esphome"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python="3.13.*"

# https://github.com/esphome/esphome
[pypi-dependencies]
esphome="==2025.11.2"
