[workspace]
channels = ["conda-forge"]
name = "esphome"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
#esphome = {python -m esphome}

[dependencies]
python="3.13.*"

[pypi-dependencies]
esphome="*"
